### ISSUE TITLE
Use of uninitialized value $generatedFiles

### ISSUE THREAD

**Issue by Gumix** [tarantool/checkpatch#76]
When `checkpatch.pl` is called for `tarantool` or `tarantool-ee` repo, it works fine. However for `tarantool-ee/tarantool` it prints:

```
$ ../../checkpatch/checkpatch.pl --git HEAD^..HEAD
Use of uninitialized value $generatedFiles in string ne at ../../checkpatch/checkpatch.pl line 2672.
Use of uninitialized value $generatedFiles in string ne at ../../checkpatch/checkpatch.pl line 2672.
Use of uninitialized value $generatedFiles in string ne at ../../checkpatch/checkpatch.pl line 2672.
```

`.gitattributes` in `tarantool-ee/tarantool` contains `src/lib/uri/uri_parser.c`, same as in `tarantool`.

**Comment by Totktonada** [comment]
I've looked into it briefly and it seems that the reason is a composition of two problems.

The first is that 2770f41d32c9a6f30c6315df61e471a1a67c5ca4 handles an empty string correctly, but an undefined `$generatedFiles` value is still possible if, for example, there is no `.gitattributes` file. We should handle it too.

The second reason is that if `.git` is a file and not a directory, then `open(<...>, ".git/../.gitattributes")` fails with the `Not a directory` error.
